apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-application
  namespace: e-commerce-website
spec:
  project: default

  source:
    repoURL: https://github.com/muralikrishna-sunkara/argocd.git
    targetRevision: HEAD
    path: ecom-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: e-commerce-website

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true